### ISSUE TITLE
Body Parser PayloadTooLargeError causes Webhooks to fail

### ISSUE THREAD

**Issue by matthew-macgregor** [Shopify/shopify-app-js#233]
# Issue summary

On our global error handler we are getting `PayloadTooLargeError` when handling some webhooks. The errors are out of our control because they are bubbling up from the Shopify App Express middleware from `body-parser`.

The `body-parser` middleware exposes the `limit` option to increase the allowed payload size, and the default is `100kb`. As you can see from the error below, this webhook payload exceeded that size. The error is actually happening in `raw-body` which `body-parser` leverages: https://github.com/stream-utils/raw-body/blob/4203bba9eb3e989bf36fd7067e58725d55126cd1/index.js#L163 when it hits the limit. Size is checked after decompression.

In the Shopify Express repo, below is the line that probably needs to change, but currently there is no way for the app to configure it.

https://github.com/Shopify/shopify-app-js/blob/35bd50b035f3449928e6ecc3281dd5068e47e70f/packages/shopify-app-express/src/webhooks/index.ts#L24

- `@shopify/shopify-app-*` package and version: 3.23.0, @shopify/shopify-app-express: 1.1.0
- Node version: `18.16.0`
- Operating system: Linux, Docker `lts-alpine:3.17`

```
PayloadTooLargeError: request entity too large
    at readStream (/app/node_modules/raw-body/index.js:156:17)
	at getRawBody (/app/node_modules/raw-body/index.js:109:12)
	at read (/app/node_modules/body-parser/lib/read.js:79:3)
	at textParser (/app/node_modules/body-parser/lib/types/text.js:86:5)
	at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
	at next (/app/node_modules/express/lib/router/route.js:144:13)
	at app.post.shopify_1.shopify.processWebhooks.webhookHandlers (/app/backend/index.js:68:5)
	at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
	at next (/app/node_modules/express/lib/router/route.js:144:13)
	at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3) {
	expected: 111657,
	length: 111657,
	limit: 102400,
    type: 'entity.too.large'
```

## Expected behavior

- A larger default probably makes sense for `express.text({type: '*/*'}),`, since some Shopify webhooks are coming in over this payload default limit.
- The limit should be configurable via the middleware.

## Actual behavior

- An error occurs in the middleware, before the webhook handler is called, which offers no opportunity to handle the problem in code.

## Steps to reproduce the problem

1. Make a `POST` request to the webhooks endpoint with a valid payload which when decompressed is greater than 100kb.

**Comment by matthew-macgregor** [comment]
I'm seeing this occurring again and the issue was auto-closed. Any chance of getting a developer's eyes on this?

**Comment by Adamekjr** [comment]
@matthew-macgregor I have same issue but on hydrogen storefront, can You tell me how to fix it?

**Comment by matthew-macgregor** [comment]
@Adamekjr  The problem is in a dependency of the Shopify Express middleware that handles webhooks. The only fix is to modify the middleware. When I get time I will fork and submit a PR, but ideally we need to get someone from Shopify to reopen this issue.

**Comment by matthew-macgregor** [comment]
@paulomarg Do you know who could take a look at this ticket?

**Comment by alihamza1214** [comment]
Hi, Getting same error even for a payload of 30kb in size for some of the requests while average requests have 3 to 10kb of size in webhooks.  Is there any workaround for this?

**Comment by dani-sanomads** [comment]
Thanks, @SeanMythen
