### ISSUE TITLE
Error after cloning an existing app

### ISSUE THREAD

**Issue by danyn** [Shopify/shopify-app-js#282]
# Issue summary

After cloning an existing app. The app crashses due to the value for the API version of rest being undefined.
The app will run by commenting out restResources so the app does not try to load it.

shopifyApp({
  api: {
    apiVersion: LATEST_API_VERSION,
    // restResources,
    billing: undefined, // or replace with billingConfig above to enable example billing
  }

"@shopify/shopify-app-express": "^1.1.0",

TOOLING AND SYSTEM                 
Shopify CLI       ^3.46.2
Package manager   npm
OS                darwin-amd64
Shell             /bin/zsh
Node version      v16.14.0

```
 LATEST_API_VERSION 2023-04
 [shopify-api/WARNING] Loading REST resources for API version undefined, which doesn't match the default 2023-04
 /Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/node_modules/@shopify/shopify-app-express/node_modules/@shopify/shopify-api/rest/load-rest-resources.js:17
         Object.entries(NewResource.HAS_ONE).map(([_attribute, klass]) => {
                ^
 TypeError: Cannot convert undefined or null to object
     at Function.entries (<anonymous>)
     at /Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/node_modules/@shopify/shopify-app-express/node_modules/@shopify/shopify-api/rest/load-rest-resources.js:17:16
     at Array.map (<anonymous>)
     at loadRestResources (/Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/node_modules/@shopify/shopify-app-express/node_modules/@shopify/shopify-api/rest/load-rest-resources.js:10:57)
     at Object.shopifyApi (/Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/node_modules/@shopify/shopify-app-express/node_modules/@shopify/shopify-api/lib/index.js:43:68)
     at shopifyApp (/Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/node_modules/@shopify/shopify-app-express/build/cjs/index.js:26:26)
     at file:///Users/danyn/Minder/Apps/new/TTKFD/ttfd-main/web/shopify.js:22:17
     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
     at async Promise.all (index 0)
     at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
 [nodemon] app crashed - waiting for file changes before starting...
```

## Expected behavior

The rest api version should be defined and the app should compile

## Actual behavior
The rest api version is undefined and the app fails

## Steps to reproduce the problem
npm run dev -> on an existing app cloned and npm installed

**Comment by chrisbenincasa** [comment]
Workaround for me was updating these two deps to these versions:

```
"@shopify/shopify-app-express": "^2.1.1",
    "@shopify/shopify-app-session-storage-sqlite": "^1.2.2",
```

**Comment by justyna-dev** [comment]
The dependency upgrade broke my app, but this workaround worked for me:

```
"@shopify/shopify-app-express": "1.1.0",
"@shopify/shopify-api": "6.1.0", // add as a new deps
```
