### ISSUE TITLE
Out of the box installation not working + Auth Admin API issues

### ISSUE THREAD

**Issue by RicSilvestre** [Shopify/shopify-app-js#484]
# Issue summary

Hello there,  I am just starting with app development, and am having issues with registering webhook, using rest admin api, and installation.
I am building an app to do the following: client selects some properties on product > when clicked on ATC button, app would calculate a price based on the choices, create a variant, send back the variant id to the theme, so that the variant can be added to the cart > order is paid > webhook to delete the created variant. I have three bigger issues currently with the node remix template.

- `@shopify/shopify-app-remix` package and version: 1.3.0
- Node version: v18.17.0
- Operating system: Windows

```
// Paste any relevant logs here
```
Log I get when I try to use await unauthenticate.admin(request):
ShopifyError: Could not find a session for shop myshoplink.myshopify.com when creating unauthenticated admin contex 

(even though I can find a session in the sessionStorage):
17:16:11 │ remix │  Session {                                                                                                           
17:16:11 │ remix │   id: '',                                                                                                           
17:16:11 │ remix │   shop: 'myshoplink.myshopify.com',                                                                    
17:16:11 │ remix │   state: '',                                                                                                        
17:16:11 │ remix │   isOnline: false                                                                                                   
17:16:11 │ remix │ }        

## Expected behavior

I expected:
- For a request that I send from an outside source and set the appropriate headers regarding cors in my app page to treat the request, authenticate it as an rest API client for me to use.
- For the app to work when I first install it, without any alterations
- For the afterAuth hook to run everytime I installed the app. It doesn't

## Actual behavior

Three bigger issues currently with the node remix template.
- The first:
I need to send product info to a page on my app (/variant-creator). I am being able to send this POST request to said page. Since it is cross origin, the app first reads it as a OPTIONS request, which goes through the loader function (seen below), then, as it clears that, it goes to the action function. In the action function, the request param I get SAYS it is a post request, but then, if I do what shopify-app-remix docs tells me to do to work with the admin api, which is: 
const { admin, session } = await authenticate.admin(request); 
It just doesn't work. It says that the OPTIONS method isn't allowed. From what I've gathered in the logs, it seems like it's redirecting to the auth/login page again, even though it already was validated in the same page, as a loader. I also tried using the solution found on [issue #936](https://github.com/Shopify/shopify-api-js/issues/936) of the shopify-api package, doesn't work either

loader function:
export const loader = async ({ request }) => { await shopify.authenticate.admin(request); return null }

- The second
I've been working in a app that I installed last week, I think. But now, if I try to install it in any other shop, or if I try to create a new app, out-of-the-box, and install it in any store, it runs the error: TypeError: Cannot read properties of undefined (reading 'statusCode')

- The third
lastly, how do I actually trigger the afterAuth hook? Because in here it seems completely at random. It should activate after I install the app, but it doesn't, and I don't know what made it activate in the few times I was able to

**Comment by jjrise** [comment]
any progress on the 2nd issue with the statusCode error?

**Comment by RicSilvestre** [comment]
> any progress on the 2nd issue with the statusCode error?

Not really. I just worked around it. This issue was happening when the app was trying to authenticate, after I installed it, it exited the iframe and went to the app page, in there the error happened, and the webhooks weren't registered. I realized at some point that I didn't need to open the app, I just needed it to have some endpoints to be accessed and with credentials that worked, so I just forced the installation not to exit the iframe, to register the app properly, and have been using it like this

**Comment by jjrise** [comment]
this is happening during the first part of the oAuth process in my '/begin' endpoint where I am running `shopify.auth.begin`. Note this has been working fine for about a year and just started happening recently.

```
⨯ TypeError: Cannot read properties of undefined (reading 'statusCode')
    at /var/task/apps/app/.next/server/app/api/shopify/uninstall/route.js:1:4687
    at Generator.next (<anonymous>)
    at /var/task/apps/app/.next/server/chunks/849.js:1:14094
    at new Promise (<anonymous>)
    at Module.h (/var/task/apps/app/.next/server/chunks/849.js:1:13843)
    at t.nodeConvertIncomingResponse (/var/task/apps/app/.next/server/app/api/shopify/uninstall/route.js:1:4614)
    at /var/task/apps/app/.next/server/chunks/3366.js:1:12042
    at Generator.next (<anonymous>)
    at s (/var/task/apps/app/.next/server/chunks/849.js:1:13899)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


```
