### ISSUE TITLE
PostgreSQLSessionStorage throw error: relation "shopify_sessions" already exists

### ISSUE THREAD

**Issue by poapy-bits** [Shopify/shopify-app-js#74]
# Issue summary

Initialize context with `PostgreSQLSessionStorage` throws error: relation "shopify_sessions" already exists.

## Expected behavior

No error.

## Actual behavior

```
2022-12-22 18:57:30 | backend  | error: relation "shopify_sessions" already exists
2022-12-22 18:57:30 | backend  |     at Parser.parseErrorMessage (.../node_modules/pg-protocol/dist/parser.js:287:98)
2022-12-22 18:57:30 | backend  |     at Parser.handlePacket (.../node_modules/pg-protocol/dist/parser.js:126:29)
2022-12-22 18:57:30 | backend  |     at Parser.parse (.../node_modules/pg-protocol/dist/parser.js:39:38)
2022-12-22 18:57:30 | backend  |     at Socket.<anonymous> (/Users/web/node_modules/pg-protocol/dist/index.js:11:42)
2022-12-22 18:57:30 | backend  |     at Socket.emit (node:events:513:28)
2022-12-22 18:57:30 | backend  |     at addChunk (node:internal/streams/readable:324:12)
2022-12-22 18:57:30 | backend  |     at readableAddChunk (node:internal/streams/readable:297:9)
2022-12-22 18:57:30 | backend  |     at Readable.push (node:internal/streams/readable:234:10)
2022-12-22 18:57:30 | backend  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2022-12-22 18:57:30 | backend  |   length: 110,

```

## Steps to reproduce the problem

using
```
"@shopify/shopify-app-session-storage-postgresql": "^1.0.1",
```

init with
```
  sessionStorage: new PostgreSQLSessionStorage(
      `postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}`)
```

on the second run. it throws errors

**Comment by paweljedrzejczyk** [comment]
This is a regression after: https://github.com/Shopify/shopify-app-js/pull/34/files
which supposed to enable multiple apps to run on same host. 

Removing `schemaname` from WHERE clause fixes it since the schemaname for newly created table is `public`, not the database name. 

My suggestion for enabling multiple apps on same host would be to supply different `sessionTableName` with app prefix, or allowing to specify the `schemaname` in options so `shopify_sessions` could be created in custom schema for each app.

**Comment by kelreel** [comment]
I have the same error, I tried to change the name of the table, it didn't help. Postgres 15.1.

**Comment by Michael-Gibbons** [comment]
Same issue, patch workaround works great @johan-aronsson thanks. Hope it's fixed soon.
