### ISSUE TITLE
Validating installation request process with "statusCode" undefined error

### ISSUE THREAD

**Issue by MyBaymax** [Shopify/shopify-app-js#767]
### Descriptions
Validating installation request process with "statusCode" undefined error
** Requesting help. Thanks！🙏 **

### Console Error Info
```shell
[shopify-api/INFO] Beginning OAuth | {shop: zhenggong.myshopify.com, isOnline: false, callbackPath: /auth/callback}
config.ts:117
TypeError: Cannot read properties of undefined (reading 'statusCode')
    at /Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/@shopify/shopify-api/adapters/node/adapter.js:23:49
    at Generator.next (<anonymous>)
    at /Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/tslib/tslib.js:165:16)
    at nodeConvertIncomingResponse (/Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/@shopify/shopify-api/adapters/node/adapter.js:21:20)
    at /Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:30:75
    at Generator.next (<anonymous>)
    at fulfilled (/Users/baymax/Desktop/onezerocom/shopify-apps/app-01-remix-vite-express/node_modules/tslib/tslib.js:166:62) {stack: 'TypeError: Cannot read properties of undefine…e-express/node_modules/tslib/tslib.js:166:62)', message: 'Cannot read properties of undefined (reading 'statusCode')'}
```

### installation request 
```javascript
http://127.0.0.1:9696/auth/login?hmac=7571c799cda164add5c0f8fc24e26e4b386d771b00a69e29429540fdfcb09c0c&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvemhlbmdnb25n&session=733696841bc1e8ad14b7933c953e1cfa8ffa91b7f05d1250ef96666cdfb28f6f&shop=zhenggong.myshopify.com&timestamp=1702215512
```

### shopify.server.ts
```typescript
import "@shopify/shopify-api/adapters/node";
import { shopifyApi, LATEST_API_VERSION } from "@shopify/shopify-api";
import { AppConfig } from "./config";

const shopify = shopifyApi({
  apiKey: AppConfig.SHOPIFY_API_KEY,
  apiSecretKey: AppConfig.SHOPIFY_API_SECRET,
  scopes: AppConfig.SCOPES.split(","),
  apiVersion: LATEST_API_VERSION,
  hostScheme: AppConfig.HOST_SCHEME,
  hostName: AppConfig.SHOPIFY_APP_URL,
  isEmbeddedApp: false,
  level: "debug",
});

export default shopify;
```

### auth.login.ts
```typescript
import type { LoaderFunctionArgs } from "@remix-run/node";
import shopify from "../shopify.server";
import { AppConfig } from "../config";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { searchParams } = new URL(request.url);
  let shop = searchParams.get("shop");
  shop = shop && shopify.utils.sanitizeShop(shop, true);
  if (!shop) return "shop is null";
  return await shopify.auth.begin({
    shop,
    callbackPath: AppConfig.CALLBACK_PATH,
    isOnline: AppConfig.IS_ONLINE,
    rawRequest: request,
  });
  return null;
};
```

**Comment by jjrise** [comment]
@MyBaymax did you ever figure this out? This is still happening to me...

**Comment by jjrise** [comment]
There seems to be a trend of this happening if I tried app installations in quick succession.
