### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'accessToken')

### ISSUE THREAD

**Issue by Kazuma7** [Shopify/shopify-app-js#771]
# Issue summary
I am developing a service using @shopify/shopify-api and when I tried to upload it to heroku and use it, I got the following error.

- `@shopify/shopify-api` version: ^7.5.2
- Node version: V18.0.0
- Operating system: MAC

```zsh
_id=96e72c2d-3f13-458d-b379-7ce30d0e4eca fwd="121.116.60.61" dyno=web.1 connect=0ms service=5ms status=204 bytes=301 protocol=https
2023-08-26T08:43:16.032938+00:00 app[web.1]: /app/node_modules/@shopify/shopify-api/lib/clients/graphql/graphql_client.js:14
2023-08-26T08:43:16.032964+00:00 app[web.1]: if (!config.isCustomStoreApp && !params.session.accessToken) {
2023-08-26T08:43:16.032965+00:00 app[web.1]: ^
2023-08-26T08:43:16.032965+00:00 app[web.1]: 
2023-08-26T08:43:16.032965+00:00 app[web.1]: TypeError: Cannot read properties of null (reading 'accessToken')
2023-08-26T08:43:16.032966+00:00 app[web.1]: at new GraphqlClient (/app/node_modules/@shopify/shopify-api/lib/clients/graphql/graphql_client.js:14:57)
2023-08-26T08:43:16.032966+00:00 app[web.1]: at new GraphqlClient (/app/node_modules/@shopify/shopify-api/lib/clients/graphql/graphql_client.js:81:5)
2023-08-26T08:43:16.032966+00:00 app[web.1]: at getGatesByShopDomain (file:///app/api/gates.js:35:18)
2023-08-26T08:43:16.032967+00:00 app[web.1]: at async getContractAddressesFromGate (file:///app/api/gates.js:5:20)
2023-08-26T08:43:16.032967+00:00 app[web.1]: at async file:///app/public-api.js:40:39
2023-08-26T08:43:16.032970+00:00 app[web.1]: 
2023-08-26T08:43:16.032971+00:00 app[web.1]: Node.js v18.17.1
```

**Comment by jonasesr** [comment]
Are there any updates. I have the same issue.
