### ISSUE TITLE
TypeError: e.toPropertyArray is not a function with @shopify/shopify-app-session-storage-postgresql

### ISSUE THREAD

**Issue by robksawyer** [Shopify/shopify-app-js#977]
# Issue summary

Before opening this issue, I have:

- [ √] Upgraded to the latest version of the relevant packages
  - `@shopify/*` package and version:
  - Node version: v20
  - Operating system: Sonoma 14.3
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration, when applicable
- [ √] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [ √] Looked for similar issues in this repository
- [√ ] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I keep getting the following error on Vercel when running the app inside of Shopify as embedded in admin.

```Error storing session: TypeError: e.toPropertyArray is not a function
    at l.storeSession (/var/task/.next/server/chunks/1693.js:39:691)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l.storeSession (/var/task/.next/server/app/api/auth/shopify/authorize/route.js:1:4479)```

## Expected behavior

I'm trying to use this CustomSessionStorage in a NextJS 14.2.3 app inside of Shopify as a Shopify App and I can't get the session to save. This issue is occurring during the beginAuth phase where accessToken is not available. I'm just not sure where toPropertyArray is even being called. 

Here is a link to my custom session storage: https://gist.github.com/robksawyer/3a345bdce7dd8ae971945d82355eaae8

**Comment by lizkenyon** [comment]
Hi there 👋 

I would recommend adding debugging logging, in the ShopifyApp configuration in your shopify.server.js file. This may help you better pinpoint when this error is happening. This error makes it sound like what is being passed into the `storeSession` function is not of type `Session`.

Setting your log level: 
```
Set { logger: { level: LogSeverity.Debug } } in my configuration, when applicable
```

**Comment by robksawyer** [comment]
I'm using a NextJS app, how would I set that in this kind of app? @lizkenyon

**Comment by lizkenyon** [comment]
You would add this to the shopifyApp config object.

```diff
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: ApiVersion.April24,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
  },
+  logger: {
+   level: LogSeverity.Debug
+  },
 ```
